# Generated by Django 4.0 on 2023-04-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
