# Generated by Django 4.0 on 2023-03-31 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParticipanteRoom',
            new_name='OnlineParticipanteRoom',
        ),
    ]
