# Generated by Django 4.0 on 2023-03-31 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_room_participante'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='limit_users',
            field=models.IntegerField(default=2),
        ),
    ]
