# Generated by Django 4.0 on 2023-04-14 21:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0007_rename_cursor_message_id_cursorparticipanteroom_cursor_begin_message_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='participante',
            field=models.ManyToManyField(blank=True, related_name='participante_in_room', to=settings.AUTH_USER_MODEL),
        ),
    ]
