# Generated by Django 4.0 on 2023-03-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_customuser_token_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='user_to',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
