# Generated by Django 4.0 on 2023-03-31 14:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_rename_customuser_tokenuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='participante',
            field=models.ManyToManyField(blank=True, related_name='participante_inroom', to=settings.AUTH_USER_MODEL),
        ),
    ]
