# Generated by Django 4.0 on 2023-03-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='token_access',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='token_refresh',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
