# Generated by Django 4.0 on 2023-03-28 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParticipanteOnline',
            new_name='ParticipanteRoom',
        ),
    ]
