# Generated by Django 4.0 on 2023-03-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_participanteonline_participanteroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participanteroom',
            old_name='date_status',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='participanteroom',
            name='user_status',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2023-03-28'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
