# Generated by Django 4.0 on 2023-04-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_cursorparticipanteroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursorparticipanteroom',
            old_name='cursor_message_id',
            new_name='cursor_begin_message_id',
        ),
        migrations.AddField(
            model_name='cursorparticipanteroom',
            name='cursor_end_message_id',
            field=models.IntegerField(default=0),
        ),
    ]
