# Generated by Django 4.0 on 2023-03-31 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chat', '0002_rename_participanteroom_onlineparticipanteroom'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='TokenUser',
        ),
    ]
